### ISSUE TITLE
range_lut: range check is incomplete

### ISSUE THREAD

**Issue by tk-ka** [Minres/SystemC-Components#25] opened 2022-02-22 11:32 UTC
The following code inside _src/common/util/range_lut.h [126:129]_ is not fully correct.
``` cpp
template <typename T> inline void range_lut<T>::addEntry(T i, uint64_t base_addr, uint64_t size) {
    auto iter = m_lut.find(base_addr);
    if(iter != m_lut.end() && iter->second.index != null_entry)
        throw std::runtime_error("range already mapped");
```

The `m_lut` container stores entries for the start and end address of every registered object (e.g. sc_register). When adding a new entry, it only checks if the demanded base address is available in `m_lut` (as start or end address of a previously added entry).

**Problem: If a new entry starts in-between the borders of existing entries, the overlap is not detected and no error is thrown.**

This case can be reproduced with the code from ticket #24 by removing register four.

**Comment by eyck** [comment] 2022-02-24 15:47
The correctness of the address map is checked in the[ validate()](https://github.com/Minres/SystemC-Components/blob/5b65d825766dd2e5359230b0451a23edaeba8d29/src/common/util/range_lut.h#L160) call  which should be called when all ranges are defined. One point would be the end_of_elaboration() or start_of_simulation() callbacks of the sc_module using the range_lut.

**Comment by tk-ka** [comment] 2022-02-25 07:07
Ok thats good: calling `range_lut::validate()` does the job. I did not recognize that function before.
It works if the custom module is a child of `scc::tlm_target` because there `socket_map` is a protected member which otherwise cannot be accessed to call `validate()`. Just something to keep in mind...

But with that the next questions comes up: Why do you check the ranges twice? First in an incomplete way inside `range_lut::addEntry()`and another time optionally but correct in `range_lut::validate()`.

**Comment by eyck** [comment] 2022-04-28 04:49
Well, it follows the fail-fast approach. If things can be checked easily then it should be done where the root cause may occur. Since the complete check is more time consuming it is done once it is ensured the information is complete. That the simple checks are executed as well is more a side-effect.

**Closed by eyck** 2022-04-28 04:49 UTC
